<!DOCTYPE html>
<html>
<head>
    <title>Audit Trail</title>
    <style>
        body { font-family: sans-serif; font-size: 10px; }
        h1 { text-align: center; margin-bottom: 5px; font-size: 16px; }
        h3 { text-align: center; margin-top: 0; font-size: 12px; font-weight: normal; margin-bottom: 20px; }
        .meta { margin-bottom: 15px; font-size: 10px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 6px; text-align: left; vertical-align: top; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .summary { margin-top: 5px; color: #555; }
    </style>
</head>
<body>
    <h1>AUDIT TRAIL</h1>
    <h3>Haiboss Inventory System</h3>

    <div class="meta">
        <strong>Generated At:</strong> {{ now()->format('d M Y H:i:s') }}<br>
        <strong>Generated By:</strong> {{ $user->name ?? 'System' }}<br>
        <strong>Total Records:</strong> {{ $records->count() }}<br>
        @if($isFiltered)
            <strong>Filter:</strong> Applied (Custom Dataset)
        @else
            <strong>Filter:</strong> All
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 15%;">Date & Time</th>
                <th style="width: 15%;">User</th>
                <th style="width: 15%;">Activity</th>
                <th style="width: 15%;">Inventory Number</th>
                <th style="width: 40%;">Summary</th>
            </tr>
        </thead>
        <tbody>
            @foreach($records as $log)
            <tr>
                <td>{{ $log->created_at->format('Y-m-d H:i:s') }}</td>
                <td>{{ $log->user?->name ?? 'System' }}</td>
                <td>
                    {{ is_object($log->action) && enum_exists(get_class($log->action)) ? $log->action->value : (is_string($log->action) ? $log->action : '') }}
                </td>
                <td>
                    {{ \Illuminate\Support\Arr::get($log->metadata ?? [], 'snapshot.inventory_number', '') }}
                </td>
                <td>
                    <div><strong>{{ \Illuminate\Support\Arr::get($log->metadata ?? [], 'snapshot.asset_name', class_basename($log->auditable_type)) }}</strong></div>
                    <div class="summary">
                        @if(in_array((is_object($log->action) ? $log->action->value : $log->action), ['MUTATION_APPROVED', 'MUTATION_REJECTED']))
                            Reason: {{ \Illuminate\Support\Arr::get($log->metadata ?? [], 'approval_note', \Illuminate\Support\Arr::get($log->metadata ?? [], 'rejection_reason', '')) }}
                        @elseif($log->parent_id)
                            Child of Audit #{{ $log->parent_id }}
                        @elseif(isset($log->metadata['old_values']) || isset($log->metadata['new_values']))
                            Changed fields: {{ implode(', ', array_keys($log->metadata['new_values'] ?? $log->metadata['old_values'] ?? [])) }}
                        @endif
                    </div>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>
